# Generated by Django 6.1.1 on 2026-10-05 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_clothes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('received', 'Received'), ('washing', 'Washing'), ('ready', 'Ready'), ('collected', 'Collected')], default='booked', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
        ),
    ]
