# Generated by Django 6.1.1 on 2026-10-06 14:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrybooking',
            name='laundry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
