# Generated by Django 6.1.1 on 2026-10-06 15:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_laundrybooking_laundry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybooking',
            name='laundry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='laundrybooking',
            name='total_clothes',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
