# Generated by Django 6.1.1 on 2026-10-06 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_alter_laundrybooking_laundry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('bedsheet', 'Bedsheet'), ('pillow_cover', 'Pillow Cover'), ('towel', 'Towel'), ('ac_towel', 'AC Towel'), ('salwar', 'Salwar'), ('kurta', 'Kurta'), ('lower_pajama', 'Lower Pajama'), ('jacket', 'Jacket'), ('sneakers', 'Sneakers'), ('jeans', 'Jeans'), ('tshirt', 'T-Shirt'), ('school_university_pant', 'School/University Pant'), ('school_university_shirt', 'School/University Shirt'), ('civil_pant', 'Civil Pant'), ('civil_shirt', 'Civil Shirt'), ('school_sweater', 'School Sweater'), ('school_coat', 'School Coat'), ('skirt', 'Skirt'), ('dupatta', 'Dupatta'), ('turban', 'Turban'), ('apron', 'Apron'), ('white_coat', 'White Coat'), ('upper_hoodie', 'Upper Hoodie'), ('small_blanket', 'Small Blanket'), ('big_blanket', 'Big Blanket')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laundry.laundrybooking')),
            ],
        ),
    ]
