# Generated by Django 6.1.1 on 2026-10-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0004_laundryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundrybooking',
            name='total_clothes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
