# Generated by Django 6.1.1 on 2026-10-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laundry', '0003_alter_laundrybooking_laundry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laundry.laundrybooking')),
            ],
        ),
    ]
